MySQL:
  Username: ""
  Password: ""
  Database: ""
  Host: ""
  
Mensagens:
  Tickets_Abertos_Scheduler: "&a[Ticket] &bExistem $tickets$ tickets abertos no momento!"
  Ticket_Numero_String: "&a[Ticket] &bOs tickets sao salvos em forma de numeros, tente novamente!"
  Ticket_Nao_Encontrado: "&a[Ticket] &bEsse ticket nao existe!"
  Ticket_Fechado_Admin: "&a[Ticket] &bO ticket foi fechado com sucesso!"
  Ticket_Fechado_Player: "&a[Ticket] &bO seu ticket de numero &b$id$ &bfoi fechado pelo staffer &a$staffer$&b!"
  Ticket_Aberto_Admin: "&a[Ticket] &bO ticket foi aberto com sucesso!"
  Ticket_Aberto_Player: "&a[Ticket] &bO seu ticket de numero &b$id$ &bfoi aberto pelo staffer &a$staffer$&b!"
  Ticket_Enviado: "&a[Ticket] &bO seu ticket foi enviado, o id de identificaçao dele é &a$id$&b, veja o status dele com /ticket status <id>"
  Ticket_Teleportado: "&a[Ticket] &bTeleportado para o local do ticket &a$id$&b!"
  Ticket_List: "&a[Ticket] &bTickets abertos no momento:"
  Ticket_Fechado_Sem_Responder: "&b[Ticket] &bEsse ticket está fechado e nao pode ser respondido!"
  Ticket_Ja_Fechado: "&a[Ticket] &bEsse ticket já está fechado!"
  Ticket_Ja_Aberto: "&a[Ticket] &bEsse ticket já está aberto!"
  Ticket_Nao_E_Seu: "&a[Ticket] &bEsse ticket nao é seu!"
  Ticket_List_Template: "&a$id$ &b- &b$player$"
  Nenhum_Ticket_Aberto: "&aNenhum ticket aberto no momento"
  Ticket_Respondido_Admin: "&a[Ticket] &bO ticket foi respondido com sucesso!"
  Ticket_Respondido_Player: "&a[Ticket] &bO seu ticket de id &b$id$ &bfoi respondido pelo staffer &a$staffer$&b!"
  Ticket_Respndido: "&a[Ticket] &bO ticket de id &a$id$ &bfoi respondido pelo player &b$player$&a!"
  Ticket_Novo: "&a[Ticket] &bO jogador &a$player$ &benviou um novo ticket!"
  Ticket_Ler:
    - "&a[Ticket] &bInformaçoes sobre o ticket &a$id$&b:"
    - "&b&lTicket status: &a$status$"
    - "&b&lTicket enviado por: &a$player$"
    - "&b&lMensagem: &a$ticket$"
    - "&b&lRespostas:"
  Ticket_Respostas_Template: "&b&l$resp$: &a$mensagem$"
  Sem_Respostas: "&aO ticket nao tem respostas ainda..."
  Default:
    - "&b[Ticket] Comandos:"
    - "&b/ticket enviar <mensagem> - &aEnvia um ticket"
    - "&b/ticket ler <id> - &aLe um ticket"
    - "&b/ticket responder <id> <mensagem> - &aResponde um ticket"